### ISSUE TITLE
Removing Aws gem dependency

### ISSUE THREAD

**Issue by luca-suriano** [WeTransfer/wt_s3_signer#1]
The signer has a runtime dependency on the `aws-sdk-s3` gem
The only place where this is (explicitly) used is here https://github.com/WeTransfer/wt_s3_signer/blob/master/lib/wt_s3_signer.rb#L138 Which is needed to get the bucket endpoint on line `44`

What if we pass the bucket endpoint to the `initialize` ? Or is the `aws-sdk-s3` gem doing anything else behind the scene?

**Comment by dennisvdvliet** [comment]
This is what it is doing: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/bucket.rb#L97
