### ISSUE TITLE
git tags for releases?

### ISSUE THREAD

**Issue by jrochkind** [WeTransfer/wt_s3_signer#8]
It is common in ruby (and suggested as common in https://semver.org/) to add a git tag for a released version. There is [one rubygems release, 0.1.0](https://rubygems.org/gems/wt_s3_signer) of wt_s3_signer, so it would be nice to have a `v0.1.0` tag in this repo. 

One thing we could easily do with it is see how much (if anything?) has changed in `master` since the last/first 0.1.0 release. Without that tag, it's cumbersome/infeasible to figure that out. (Looking at the commit history it looks like there are few significant commits since the date of 0.1.0 release, so probably not?)

Would you consider using version tags in the future? If you use the `rake release` task that can be provided by bundler to do your releases, it adds and pushes a git tag automatically. 

If it's still retrievable what git sha corresponds to the 0.1.0 release, it would still be helpful to tag!

**Comment by julik** [comment]
Good point! Going forward the tags should get applied automatically, but 0.1.0 has to retroactively tagged, I'll take care of this.
